service: http-serverless-api

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: dev
  region: ap-northeast-2
  deploymentBucket: wannavi-serverless-hands-on-1
  environment:
    NODE_ENV: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:*"

plugins:
  - serverless-apigw-binary
custom:
  apigwBinary:
    types:
      - "application/json"
      - "text/html"

functions:
  webapp:
    handler: src/handler.api
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: OPTIONS
          cors: true
